---
# a unix path-friendly name (IE, no spaces or special characters)
project_name: django_project

# the base path to install to. You should not need to change this.
install_root: /home/ormuco_challenge

# the python module path to your project's wsgi file. E.g. for a directory
# layout like this (assuming `django_hello` is the project_name and top level
# directory name):
# django_hello
# +-- hello
# ¦   +-- apps
# ¦   +-- __init__.py
# ¦   +-- settings.py
# ¦   +-- urls.py
# ¦   +-- wsgi.py
# +-- manage.py
# +-- requirements.txt
# the correct wsgi_module value would be `hello.wsgi`
wsgi_module: django_project.wsgi

# any directories that need to be added to the PYTHONPATH.
pythonpath: "{{ install_root }}/{{ project_name }}/ormuco/apps"

# the git repository URL for the project
project_repo: https://github.com/mpotey1/ormuco

# a private key that has access to the repository URL
ssh_private_key: ~/.ssh/key

# The value of your django project's STATIC_ROOT settings.
# This will be the directory that django's `collectstatic` management command
# copies static files to, and it must be an absolute path. The default value
# here assumes that STATIC_ROOT is set in your settings.py like so:
# STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, 'static'))
static_root: "{{ install_root }}/{{ project_name }}/static"

# the dns name or names (space separated) for your server
server_name: #enter server's ip

# database setup. Note that because this playbook doesn't touch the default
# postgres pg_hba.conf file, we use local password-based authentication for
# postgres and thus you need to provide a username and password, and your
# settings.py MUST set "localhost" or "127.0.0.1" as the HOST value. For
# example, the default settings here assume the following values in
# settings.py:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'HOST': 'localhost',
#         'NAME': 'hello',
#         'USER': 'hello',
#         'PASSWORD': 'changeme',
#     }
# }
db_name: django
db_user: django
db_password: c089463b2f0378bb86dd5cbb9fa836a5

# apt packages, you should not need to change this unless you have packages
# listed in your requirements.txt that depend on system packages.
system_packages:
  - git
  - python-pip
  - python-dev
  - nginx
  - gunicorn
  - sqlite3
  - libsqlite3-dev
  - python-psycopg2

# vim:ft=ansible:


